# Generated by Django 2.2 on 2020-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('money', models.PositiveIntegerField(verbose_name='Сумма пополнения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата пополнения')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_id', models.CharField(max_length=255, verbose_name='Ид платежа')),
                ('bonus', models.PositiveIntegerField(default=0, verbose_name='Сумма бонуса')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
